name: React CI

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod


jobs:
  name: Merge Test
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Build
        run: npm run build-ci
      - name: Run Test Suite
        run: npm test
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
